### PR TITLE
Add queries

### PR DESCRIPTION
**Pull request by shakerAbuDrais**
I have created a new database called vet-clinic
and created a new table in that database. 

populated the required data and made screenshots for the queries results

image
image
image

### CODE REVIEW

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @shakerAbuDrais 👋, 

Good job so far!

### Highlights
- All codes for creating, structuring and altering tables are in the _**schema.sql**_ file ✔️ 
- All codes that populate tables with data are in the _**data.sql**_ file ✔️ 
- All codes that query or help to analyze data are in the _**queries.sql**_ file ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
Kindly make the following changes:

- [ ] Please update the pull request description with the results of the screenshots of each query statement written in the queries.sql file. This way, we can confirm if your queries returned the correct data. 👍 
- [ ] Kindly fix the `MIT` link of your README.md file. It shows a 404 error page when it is clicked. 👍 

image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by shakerAbuDrais** [comment]
@Gambit142 am really sorry, your first comment is really not understood, can't you see the results of the queries in the screenshots?

**Comment by shakerAbuDrais** [comment]
@Gambit142 you can clearly see in the last screenshot, that it returned the correct data which means the table was created and data were pushed to it, and I have the same results for the queries like all other students so i don't understand why you put that comment

**Review by tufoinnkuo10 — CHANGES_REQUESTED** [review]
Hi @shakerAbuDrais 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ Querry screenshots ok
✅ Descriptive pull request message
✅ Documented your work professionally


Required Changes ♻️
- [ ] like the previous reviewer noted,Kindly fix the MIT link of your README.md file. It shows a 404 error page when it is clicked.
 we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish.


Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by Gambit142** [comment]
> @Gambit142 you can clearly see in the last screenshot, that it returned the correct data which means the table was created and data were pushed to it, and I have the same results for the queries like all other students so i don't understand why you put that comment

Hi @shakerAbuDrais, I am talking about the result of each query you wrote in your `queries.sql` file. Kindly include them. The result you have is of one query

**Review by Ismailco — APPROVED** [review]
### Hi @shakerAbuDrais, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

cr-approve


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
